bot:
  bot-username: SVURoutesBot
  token: ${BOT_TOKEN}
  admin-chat-id: ${ADMIN_CHAT_ID}
  review-chat-id: ${REVIEW_CHAT_ID}
  suggestion-chat-id: ${SUGGESTION_CHAT_ID}
content:
  filename:
    messages: messages.json
    routes: routes.json
    dots: dots.json
keyboard:
  max-buttons-in-row: 1
message:
  split-dot-messages: false
  show-dots: true
  show-routes: true
server:
  address: 0.0.0.0
  port: 10000
spring:
  application:
    name: SVURoutesBot
  output:
    ansi:
      enabled: always
  datasource:
    url: ${JDBC_STRING}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false